### ISSUE TITLE
Disposing muted video track throws an exception for unified plan (safari)

### ISSUE THREAD

**Issue by ashitikov** [jitsi/lib-jitsi-meet#1105]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
We have a custom UI, built on lib-jitsi-meet. 
I will try to explain how we use api of library in user case:
1. User tap to unmute video for the first time, we create video track, then add it to conference.
2. User tap to mute video, we use localVideoTrack.mute()
3. User tap to unmute screensharing, we call localVideoTrack.dispose(), then create desktop track and add it to conference.

This happens for me only in safari (not tested with other browsers with unified plan).

## Current behavior
In the last step we get an exception: "RTCRtpTransceiver for video not found"
![dispose_track_error](https://user-images.githubusercontent.com/8819544/79692914-e81b2180-8278-11ea-9961-d3bb97995042.png)

## Expected Behavior
No exception.

## Possible Solution
I found that this exception throws at https://github.com/jitsi/lib-jitsi-meet/blob/3e205750488a11df9c5d95ce028e50761b30447d/modules/RTC/TPCUtils.js#L252 .
So for now, to get it working, we changed our workflow, and when user taps to mute video, we call localVideoTrack.dispose() instead of localVideoTrack.mute() - in this case everything is okay.

## Steps to reproduce
I don't know how to reproduce this on jitsi-meet, because, on a minimal research, I found, that instead of disposing video track, jitsi-meet use replaceTrack(videoTrack, desktopTrack). So I guess it's not reproducable now on jitsi-meet.

This could be reproducable on example, but it should be modified as well to support mute/unmute video with the case in description above.

# Environment details
Latest jitsi's server stack.
lib-jitsi-meet, built from this commit: https://github.com/jitsi/lib-jitsi-meet/commit/e4838d319f0022d79aea9f88518d11991af6f540

**Comment by jallamsetty1** [comment]
Thank you for the report and the analysis. In step 3, how are you adding the desktop track to the conference ?

**Comment by ashitikov** [comment]
> Thank you for the report and the analysis. In step 3, how are you adding the desktop track to the conference ?

`conference.replaceTrack(null, desktopLocalTrack)`
also tried `conference.addTrack(desktopLocalTrack)`, got the same behavior.

The exception happens when you dispose MUTED videoTrack (previously called videoTrack.mute() ), not on adding desktop track to the conference.
On the other hand, exception do not throw if you try to dispose UNMUTED videoTrack.

**Comment by ashitikov** [comment]
Today found, when you dispose UNMUTED videoTrack without any exceptions on safari, you will not be able to get TRACK_REMOVED event on the remote side, but MediaStreamTrack will have muted: true flag instead.

**Comment by ashitikov** [comment]
Also, don't know why but `capScreenshareBitrate: true` makes screensharing from safari interrupted (after some time remote track get onmute event, participant status conn move from active to restoring and nothing happens). Instead, `capScreenshareBitrate: false` makes screensharing working (also got sometimes onmute event, but conn then seems restoring), but with very bad quality.

Also posted a bad case for chrome here: https://community.jitsi.org/t/is-someone-working-on-safari-compatibility/22668/38?u=ashitikov

**Comment by jallamsetty1** [comment]
> > Thank you for the report and the analysis. In step 3, how are you adding the desktop track to the conference ?
> 
> `conference.replaceTrack(null, desktopLocalTrack)`
> also tried `conference.addTrack(desktopLocalTrack)`, got the same behavior.
> 
> The exception happens when you dispose MUTED videoTrack (previously called videoTrack.mute() ), not on adding desktop track to the conference.
> On the other hand, exception do not throw if you try to dispose UNMUTED videoTrack.

Ok, look like we are trying to remove the track from the peerconnection twice, first when its muted and then when its disposed. The second remove shouldn't be happening, looks like it didn't matter for plan-b case. I will hopefully get to this sometime this week. Thanks !

**Comment by jallamsetty1** [comment]
> Also, don't know why but `capScreenshareBitrate: true` makes screensharing from safari interrupted (after some time remote track get onmute event, participant status conn move from active to restoring and nothing happens). Instead, `capScreenshareBitrate: false` makes screensharing working (also got sometimes onmute event, but conn then seems restoring), but with very bad quality.
> 
> Also posted a bad case for chrome here: https://community.jitsi.org/t/is-someone-working-on-safari-compatibility/22668/38?u=ashitikov

We disable simulcast on desktop track when `capScreenshareBitrate` is set to true. This is because of the desktop share freezes we were seeing on chrome when simulcast is turned on (chrome). Looks like Safari has issues when simulcast is turned off. Thank you for reporting these issues, we will start working on them one after the other now that safari signaling is fixed.

Also, about the audio issue with chrome reload, we are aware of these audio issues and someone from the team will be taking a look.

**Comment by ashitikov** [comment]
Thank you much for the detailed explanation.

**Comment by ashitikov** [comment]
Don't know why, but when I changed transport from websocket to BOSH, audio issues as well as desktop share freezes has gone. Seems that websocket is not so stable now.

**Comment by jallamsetty1** [comment]
Thank you for this feedback! It’s very helpful in troubleshooting the safari issues, will discuss with the team and run some more tests.

**Comment by jallamsetty1** [comment]
> Don't know why, but when I changed transport from websocket to BOSH, audio issues as well as desktop share freezes has gone. Seems that websocket is not so stable now.

Hey @ashitikov, I am not able to reproduce the desktop share freeze issues on meet.jit.si, everything seems fine if I don't turn on the presenter. Also, I tried changing the transport to BOSH and I am still seeing the audio issue that you had reported earlier, i.e., when the chrome client reloads, audio is lost on Safari. Did switching to BOSH fix this particular issue for you ?

**Comment by ashitikov** [comment]
> > Don't know why, but when I changed transport from websocket to BOSH, audio issues as well as desktop share freezes has gone. Seems that websocket is not so stable now.
> 
> Hey @ashitikov, I am not able to reproduce the desktop share freeze issues on meet.jit.si, everything seems fine if I don't turn on the presenter. Also, I tried changing the transport to BOSH and I am still seeing the audio issue that you had reported earlier, i.e., when the chrome client reloads, audio is lost on Safari. Did switching to BOSH fix this particular issue for you ?

After some time, I can say that switching to BOSH helped partially - sometimes audio issues still reproduce, but I can't catch the moment when it is happening. But with websocket it was stable. I don't know how transport affects tracks behavior. Maybe websocket is a bit more faster and the problem is in timings. 

So I can confirm that audio issue still exists but less stable if you switch to BOSH. 
What about desktop share freezes - I can't reproduce freezes on BOSH for now, but if these 2 problems are linked to each other, I think it is also unstable.

Thank you, for your attention.

**Comment by jallamsetty1** [comment]
Safari audio should be fixed - #1132

**Comment by ashitikov** [comment]
Thank you!

> Today found, when you dispose UNMUTED videoTrack without any exceptions on safari, you will not be able to get TRACK_REMOVED event on the remote side, but MediaStreamTrack will have muted: true flag instead.

Will #1132 fix this issue?

**Comment by jallamsetty1** [comment]
> Thank you!
> 
> > Today found, when you dispose UNMUTED videoTrack without any exceptions on safari, you will not be able to get TRACK_REMOVED event on the remote side, but MediaStreamTrack will have muted: true flag instead.
> 
> Will #1132 fix this issue?

No, that is a separate issue, I haven't been able to get to it, will hopefully fix it this week. Thanks for your patience :)

**Comment by ashitikov** [comment]
Finally, I found a problem for screensharing and in fact, it absolutely does not depend on unified plan. Im sorry that I included this as an issue here. The actual problem was that selectParticipant did not invoke properly for some participants and videobridge after some time just suspend a video.

Thank you much for attention!

**Comment by ashitikov** [comment]
Hi @jallamsetty1 is there any progress on this issue? Can I help?

**Comment by jallamsetty1** [comment]
> Hi @jallamsetty1 is there any progress on this issue? Can I help?

Sorry not yet, will do it today.

**Comment by jallamsetty1** [comment]
@ashitikov Can you please check if you are reproducing this issue with latest lib-jitsi-meet ? We did some refactoring in the past few weeks which I believe should resolve this issue.

**Comment by jallamsetty1** [comment]
@ashitikov, I believe this should have been fixed, please feel free to re-open the bug if you are able to reproduce the issue still.

**Comment by sapkra** [comment]
@jallamsetty1 I received this error about a week ago (October 8, 2020) on Mobile Safari (iOS 14.0) but after the error `Bridge Channel send: no opened channel`. So I guess it's still not fixed or it has a different cause in my case.

![image](https://user-images.githubusercontent.com/8087568/96275381-f5b82680-0fd1-11eb-8a53-73d6afb77f50.png)

**Comment by ashitikov** [comment]
@jallamsetty1 now I don't have exception, but disposing track on safari gives black screen on a chrome's side because TRACK_REMOVED do not get called. I suppose that I could reopen this bug.

**Comment by usamashahid049** [comment]
@jallamsetty1 I am getting the same exception on safari. I have a custom UI built on lib-jitsi-meet. This exception appears when we remove the camera track. 

![Screenshot 2021-06-02 at 10 49 04 AM](https://user-images.githubusercontent.com/50103811/120433192-5eeb7f00-c394-11eb-93fc-647498c1ea40.png)

**Comment by jallamsetty1** [comment]
> @jallamsetty1 I am getting the same exception on safari. I have a custom UI built on lib-jitsi-meet. This exception appears when we remove the camera track.
> 
> ![Screenshot 2021-06-02 at 10 49 04 AM](https://user-images.githubusercontent.com/50103811/120433192-5eeb7f00-c394-11eb-93fc-647498c1ea40.png)

Can you please try with the latest ? This has been fixed in the tip already.

**Comment by usamashahid049** [comment]
I am following the [lib-jitsi-meet API (low level)](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api).I am assuming documentation is updated. Am I right? If not, can you please provide the updated version link.

**Comment by jallamsetty1** [comment]
@usamashahid049 Yes, I am talking about the low level lib-jitsi-meet API. What version of the library are you using ? commit 5fcd419dcf706f81b1958188b8650c5647afe66d should have all the fixes.

**Comment by usamashahid049** [comment]
@jallamsetty1  I am using jisti-meet-lib by adding this script <script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>
I think this is getting the latest version of jisti-meet-lib. Isn't it?

**Comment by sapkra** [comment]
@usamashahid049 It's the latest released version but not really the latest version. The commit mentioned by @jallamsetty1 is not in a stable build yet.

**Comment by usamashahid049** [comment]
@sapkra  When will this commit be available for the latest released version?

**Comment by jallamsetty1** [comment]
@usamashahid049 The fix will probably be deployed to meet.jit.si by early next week.

**Comment by usamashahid049** [comment]
When is this available for the released version?
And Can it possible in lib-jitsi-meet(Low-level API) to share a video and screen at the same time?

**Comment by jallamsetty1** [comment]
The fix has been deployed on meet.jit.si and will be pushed to stable in the next few days. 
No, right now there is no way to send a camera and desktop track separately at the same time.
