### ISSUE TITLE
React native + lib-jitsi-meet - audio/video tracks not getting added to the conference

### ISSUE THREAD

**Issue by s-xync** [jitsi/lib-jitsi-meet#1296]
Firstly, thanks to the entire Jitsi team and the community for such an awesome project. 

We are trying to create a react native mobile app for Jitsi from scratch using lib-jitsi-meet api and we have a self-hosted jitsi-meet on AWS server and we followed [quick-install guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart). For the purpose of this post, the URL is `https://jitsimeet.example.com`.

In the react native app, we are able to join a conference called `test1` using `JitsiMeetJS.initJitsiConference`. Once joined, the user is visible as "Fellow Jitster" on the browser at `jitsimeet.example.com/test1` **but the tracks(video/audio) we are adding to the conference(from react native mobile app) are not visible and in the browser and it just says "Participant has stopped the camera" and "Participant is muted"**.

We have tried `meet.jit.si` & `beta.meet.jit.si` in our react native app to see if the problem is related to our backend installation. But these were also not working.

We have also tried the same conference `jitsimeet.example.com/test1` on the browser and in jitsi-meet mobile app and they are both working fine without any issues.

We have also set up [jitsi-meet](https://github.com/jitsi/jitsi-meet) repository locally. On running the react-native part on android emulator, it is working fine(both joining the conference & rendering the audio/video tracks).

From the above observations, it seems to be that the issue is coming from our implementation of react native app.

Our code for the component that initiates the conference can be found [here](https://github.com/s-xync/rn-jitsi-poc/blob/master/screens/ClassScreen/ClassScreen.js). Here you can find the link to [our repo](https://github.com/s-xync/rn-jitsi-poc). To run it, just do `npm i` and `npx react-native run-android`. We are using polyfills in our react-native code as given in the [jitsi-meet](https://github.com/jitsi/jitsi-meet) repository.

In the logs of jicofo on our server,

We were able to see that when users join via web or jitsi-meet mobile app, we are getting

```
org.jitsi.jicofo.ParticipantChannelAllocator.log() Sending session-initiate to: test1@conference.jitsimeet.example.com/2502e6ad
org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Got session-accept from: test1@conference.jitsimeet.example.com/2502e6ad
org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Received session-accept from test1@conference.jitsimeet.example.com/2502e6ad with accepted sources:Sources{ video: [ssrc=467278592 ssrc=2301072636 ssrc=839807103 ssrc=3616291734 ssrc=2331517151 ssrc=3181098946 ] audio: [ssrc=2795704819 ] }@2129717334
```
whereas when we join via our react native app, we are only getting
```
org.jitsi.jicofo.ParticipantChannelAllocator.log() Sending session-initiate to: test1@conference.jitsimeet.example.com/946022e6
```

#### Just to provide more information which might be relevant

On the client side, we are adding tracks after `CONFERENCE_JOINED` event is fired, then, we are getting the following logs

```
[JitsiConference.js] _doReplaceTrack - no JVB JingleSession
[JitsiConference.js] _doReplaceTrack - no P2P JingleSession
```

As mentioned above, we can join the conference from our react native app and we are getting `CONFERENCE_JOINED`, `USER_JOINED`, `USER_LEFT` events.

The `TRACK_ADDED` event is also firing locally right after adding local tracks. But it is not firing for any video/desktop-sharing/audio changes occurring on other remote clients(web browser or jitsi-meet mobile app). 

We have spent a week trying to fix this issue without any breakthroughs so far. Any guidance on this is greatly appreciated.

Thank you.

**Comment by paweldomas** [comment]
```
[JitsiConference.js] _doReplaceTrack - no JVB JingleSession
[JitsiConference.js] _doReplaceTrack - no P2P JingleSession
```

It means there are no media sessions and you won't get remote tracks added events without them.

**Comment by s-xync** [comment]
@paweldomas can you give some direction as to what needs to be done. to create media sessions? Currently, I am creating a conference and after the `CONFERENCE_JOINED` event is fired, I am adding tracks. Is there something I am doing wrong or something that I am missing?

**Comment by paweldomas** [comment]
You should check Jicofo logs if it sees participants joining

**Comment by s-xync** [comment]
I have also included the Jicofo logs in the issue description. It seems that when we are using a web browser for the conference `jitsimeet.example.com/test1`, it gives `session-initiate` and `session-accept` logs for each user joining the conference. Whereas when I am joining the same conference through our react-native implementation, it **only** give `session-initiate` log and there is **no** `session-accept` log coming. I am unable to figure out what might be causing this issue. Could you please if you have some time, look into the code located [here](https://github.com/s-xync/rn-jitsi-poc/blob/master/screens/ClassScreen/ClassScreen.js) and tell me if I am doing something wrong in using lib-jitsi-meet. Thanks.

**Comment by s-xync** [comment]
@paweldomas 

After further investigation, I found that there is an issue occurring when jingle session is being initialized in lib-jitsi-meet.

After Jicofo sends `session-initiate`, in the file [JitsiConference.js](https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js), in the function `JitsiConference.prototype._acceptJvbIncomingCall`, when `jingleSession.initialize` is being called, is throwing the following error:
```
{
    "error": [TypeError: undefined is not an object (evaluating 'eventTarget[LISTENERS][type]')],
    "message": "undefined is not an object (evaluating 'eventTarget[LISTENERS][type]')",
    "name": "TypeError",
    "stack": "setAttributeListener@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:110008:38
set@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:110051:31
_RTCPeerConnection@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:111610:9
R@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:183673:687
createPeerConnection@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:167562:30
doInitialize@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:172093:105
initialize@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:182236:79
_acceptJvbIncomingCall@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:176712:30
onIncomingCall@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:176694:40
[native code]
emit@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:168799:38
onJingle@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:181297:216
onJingle@[native code]
run@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:164553:33
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:164807:78
forEachChild@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:164255:88
_dataRecv@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:164799:33
_dataRecv@[native code]
_onRequestStateChange@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:165337:285
_onRequestStateChange@[native code]
bound _onRequestStateChange@[native code]
dispatchEvent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:34489:31
setReadyState@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:33558:27
__didCompleteResponse@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:33400:29
emit@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3702:42
__callFunction@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3030:49
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2752:31
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2984:15
callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2751:21
callFunctionReturnFlushedQueue@[native code]"}
```

I don't know if this is an issue that I am somehow causing because in the jitsi-meet official react native app, jingle session is being initialized without any problem.

I am also including the entire frontend log [here](https://gist.github.com/s-xync/5da8633dec69f3f2f84d26a9041d7c01). The log also has the parameters that were used by `jingleSession.initialize`.

If you have some time, please guide me on what needs to be done to resolve this issue.

**Comment by m-ayush** [comment]
Have anyone integrated lib jitsi meet with react js , please send me the link.

**Comment by thiagobrez** [comment]
I can second this. Using react-native I only receive local tracks on `TRACK_ADDED` listener

**Comment by thiagobrez** [comment]
Actually after further investigation I'm having the exact same issue. `CONFERENCE_JOINED` is triggered, but `JingleSession` logs appear too

```
[JitsiConference.js] _doReplaceTrack - no JVB JingleSession
[JitsiConference.js] _doReplaceTrack - no P2P JingleSession
```

**Comment by vinh-smartdev** [comment]
I actually have the same issue. As long as the second one join the conference, the error shows up

**Comment by samelm** [comment]
Has anything become known about this problem?

**Comment by thiagobrez** [comment]
I've also reproduced this problem on a clean repo (see https://github.com/thiagobrez/react-native-jitsi-test)

and opened a ticket at community.jitsi.org (https://community.jitsi.org/t/react-native-cannot-read-property-addstream-of-undefined/82453/3).

Could someone take a look? @paweldomas @saghul 

It's a minimal app with a TextInput to connect to a Jitsi beta server room.

Please note that the `lib-jitsi-meet` fork that I'm using just removed the `postinstall` script to avoid `webpack` errors discussed in other issues. On the README, I've included instructions to running and generating `lib-jitsi-meet.min.js`.

If I get this working I'd be happy to contribute to the docs with a tutorial to installing lib-jitsi-meet on React Native.

Thanks!

**Comment by kait-baraa** [comment]
any update on this please? is there any implementation that is working for lib-jitsi-meet with react native?

**Comment by suvankar-daffodil** [comment]
facing the same issue, any leads on this? correct me if I am wrong but I think it has something to do with the polyfills

**Comment by arungirivasan97** [comment]
i also have same issue. any update on this?

**Comment by baraa95** [comment]
**issue Solved** ... just replace the RTCPeerConnection file with the following 

[https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js](url) 

Working for both android and iOS

**Comment by suvankar-daffodil** [comment]
> **issue Solved** ... just replace the RTCPeerConnection file with the following
> 
> [https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js](url)
> 
> Working for both android and iOS

changing the ios file will solve it for android as well?

**Comment by baraa95** [comment]
@suvankar-daffodil YES, it will work on both android and iOS 👍

**Comment by aweffr** [comment]
> **issue Solved** ... just replace the RTCPeerConnection file with the following
> 
> [https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js](url)
> 
> Working for both android and iOS

It works! Thank you very much!

**Comment by danghung24031992** [comment]
> **issue Solved** ... just replace the RTCPeerConnection file with the following
> 
> [https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js](url)
> 
> Working for both android and iOS

please, share again , this link not working

**Comment by tang4** [comment]
> **issue Solved** ... just replace the RTCPeerConnection file with the following
> 
> [https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js](url)
> 
> Working for both android and iOS

👌

**Comment by s-xync** [comment]
@baraa95 solution is working. Just to make it clear, in your polyfills folder you have 'RTCPeerConnection.js'. Just replace the contents of this file with the contents of https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js. Then it will take effect for both Android and iOS. Just to make it clear again, no need to change the file name only change the contents.

**Comment by s-xync** [comment]
@saghul @paweldomas @damencho - the 'RTCPeerConnection.js' file in the polyfills folder was last edited a year back and I don't know how you guys are not facing any issue but whenever we try to integrate into our apps, we faced this issue. This issue was raised 10 months back. I'm marking it resolved now. Please have a look at the solution mentioned in this forum and if possible please incorporate the changes into the actual jitsi-meet codebase. Thanks.

**Comment by buddhiv** [comment]
> Have anyone integrated lib jitsi meet with react js , please send me the link.

I am currently working on a project with lib-jitsi-meet and react.js (for web). I'm happy to help if there is anything.

**Comment by buddhiv** [comment]
> > Have anyone integrated lib jitsi meet with react js , please send me the link.
> 
> I am currently working on a project with lib-jitsi-meet and react.js (for web) and have successfully integrated both. I'm happy to help if there is anything.

**Comment by vantuan88291** [comment]
2022 and still got this error event change [RTCPeerConnection.ios.js](https://github.com/uppuluriaditya/RTCPeerConnection/blob/main/RTCPeerConnection.ios.js)

**Comment by saghul** [comment]
The original issue was solved, there is no need to override that file. You must be seeing a different issue.

**Comment by tuanlvntq** [comment]
> 

still not resolve, I was get all polyfills latest code at Jitsi-meet repo but still happened
