### ISSUE TITLE
Distorted audio in Mobile Safari (IOS 14.2)

### ISSUE THREAD

**Issue by nadelicious** [jitsi/lib-jitsi-meet#1407]
## Description
  Distorted audio will be experienced at the beginning of the call when using Mobile Safari (IOS 14.2). 

## Current behavior
You can hear distorted audio for a few seconds usually started at the beginning of the call.

## Expected Behavior
Distorted audio should not be experienced by the user when using Mobile Safari  (IOS 14.2).

## Possible Solution
No current solution as of this moment.
## Steps to reproduce
Join the call with more than 2 participants using mobile safari with IOS version 14.2. The issue can be experienced also in desktop Safari 14.0.1

# Environment details
**Config**
 ```
p2p: {
    enabled: false,
}
disableSimulcast: true 
```
***Devices used***
IPhone 12, Iphone X, Iphone 8, Safari 14.0.1 desktop

**Comment by jallamsetty1** [comment]
@nadelicious Apparently this has been fixed in iOS 14.3.

**Comment by nadelicious** [comment]
@jallamsetty1  thanks.

**Comment by MrOscarKi** [comment]
Problem persist in Safari 14.0.1 (macOS Big Sur 11.0.1, MacBook 12-inch Early 2016)

**Comment by sapkra** [comment]
@nadelicious 14.3 is out now. Can you try to reproduce it with that version?

**Comment by MrOscarKi-Sudameris** [comment]
I tested on iOS 14.3 and macOS Big Sur 11.1, and the problem is fixed! 🎉

**Comment by nadelicious** [comment]
Confirmed. The issue is fixed.
